# Nom de l'application
spring.application.name=fast-food-api

# Configuration serveur
server.port=8080

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/... <============
spring.datasource.username=postgres
spring.datasource.password=0907
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
# 'validate' vérifie que le schéma de la BD correspond aux entités Java sans le modifier
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
