TRUNCATE TABLE
    commandes_fournisseurs_details,
    recette,
    catalogue_fournisseur,
    commandes_fournisseurs,
    employe_heure,
    employe,
    commandes_menu,
    commandes,
    panier_items,
    panier,
    email_verification_tokens,
    adresse,
    produit_menu,
    stock_matiere_premiere,
    categorie,
    fournisseur,
    option_groupe,
    option_item,
    panier_item_options,
    commande_item_options,
    users
RESTART IDENTITY CASCADE;